### ISSUE TITLE
Installation Issue - can't change admin password

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#243] opened 2012-08-23 16:28 UTC
Can't change admin password

(browser: Firefox 14.0.1)

SWIFTRIVER: ErrorException [ Notice ]: Undefined index: current_password

APPPATH/classes/controller/user.php [ 355 ]

350  
351     private function _update_settings()
352     {  
353         // Validate current password
354         $validated = FALSE;
355         $current_password = $_POST['current_password'];
356         if ($this->riverid_auth)
357         {
358             $response = RiverID_API::instance()->signin($this->user->email, $_POST['current_password']);
359             $validated = ($response AND $response['status']);
360         }

```
APPPATH/classes/controller/user.php [ 355 ] > Kohana_Core::error_handler(arguments)

APPPATH/classes/controller/user.php [ 343 ] > Controller_User->_update_settings()

{PHP internal call} > Controller_User->action_settings()

SYSPATH/classes/kohana/request/client/internal.php [ 116 ] > ReflectionMethod->invoke(arguments)

SYSPATH/classes/kohana/request/client.php [ 64 ] > Kohana_Request_Client_Internal->execute_request(arguments)

APPPATH/classes/request.php [ 59 ] > Kohana_Request_Client->execute(arguments)

DOCROOT/index.php [ 118 ] > Request->execute() 
```

**Comment by otsuarez** [comment] 2012-09-28 02:35
hi, a workaround i found for this issue was, in themes/default/views/pages/user/js/settings.php, change [this line](https://github.com/ushahidi/SwiftRiver/blob/master/themes/default/views/pages/user/js/settings.php#L12):
var pass = $('article.modal input[name=current_password_prompt]').filter(":visible").val()
for this (renaming the POST variable without the  _prompt):
var pass = $('article.modal input[name=current_password]').filter(":visible").val()

**Comment by ekala** [comment] 2012-10-17 07:44
@dan-king @otsuarez I was unable to reproduce this behaviour - on an install running off the latest code from the `master` branch - on both Firefox (15.0.1) and Chrome.

Closing but please re-open if the issue still persists.

**Closed as completed by ekala** 2012-10-17 07:44 UTC
